config/routes.rb
Rails.application.routes.draw do 
  root 'cars#index'
  resources :manufacturers do 
  	resources :cars
  end
end

app/models/car.rb
class Car < ActiveRecord::Base
	belongs_to :manufacturer
	validates :mname, presence: true, length: { minimum: 4 }
	validates :color, presence: true, length: { minimum: 4 }
	validates :year, inclusion: { in: 1920..2050 }
	validates :mileage, presence: true
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
	has_many :cars
	validates :name, presence: true, length: { minimum: 4 }
	validates :country, presence: true, length: { minimum: 3 }
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

	def index
		@car = Car.all
	end

	def show
		@car = Car.find(params[:id])
	end

	def new
		@manufacturers = Manufacturer.all
		@car = Car.new
		@mid = Manufacturer.find(params[:manufacturer_id])
	end

	def create
		@mid = Manufacturer.find(params[:manufacturer_id])
		@car = Car.new(car_params)	
		if @car.save
			redirect_to manufacturer_cars_path, notice: 
			"Your car was successfully posted."
		else
			render :new
		end	
	end

	private
	def car_params
		params.require(:car).permit(:mid, :mname, :color, :year, :mileage, :description)
	end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  
  def index
  	@man_u = Manufacturer.all
  end

  def new
  	@man_u = Manufacturer.new
    @car = Car.new
  end

  def create
  	@man_u = Manufacturer.new(man_u_params)
		if @man_u.save
			redirect_to root_path(@man_u[:id]), notice: 

			"Your Manufacturer was successfully posted."
		else
		  render new_manufacturer_path
		end	
  end

  def show
  	@man_u = Manufacturer.find(params[:id])
  end

  private

	def man_u_params
		params.require(:manufacturer).permit(:name, :country)
	end

end

app/views/cars/index.html.erb
<h3> Index of existing cars </h3>
<% @car.each do |car| %>
<ul>
	<%= car.year %> <%= link_to car.mname, manufacturer_car_path(car.mid, car.id) %>
</ul>
<% end %>

app/views/cars/new.html.erb
<%= form_for ([@mid, @car]) do |f| %>	
	<%= f.hidden_field :mid, value: @mid %>	
	<div>
		<%= f.label :mname, "Model (Required)" %>
		<%= f.text_field :mname %>
	</div>
	<div>
		<%= f.label :color, "Color (Required)" %>
		<%= f.text_field :color %>
	</div>
	<div>
		<%= f.label :year, "Year (Must be greater than 1920)" %>
		<%= f.text_field :year %>
	</div>
	<div>
		<%= f.label :mileage, "Mileage (Required)" %>
		<%= f.text_field :mileage %>
	</div>
	<div>
		<%= f.label :description, "Description (Optional)" %>
		<%= f.text_area :description %>
	</div>
	<div>
	<%= f.submit "submit" %>
	</div>
	<% if @car.errors.any? %>
  	<div id="error_explanation">
    <h4><%= pluralize(@car.errors.count, "error") %>: Please review </h4> 	
  	<ul>
  	<% @car.errors.full_messages.each do |msg| %>
  		<li><%= msg %></li>
  	<% end %>
  	</ul>
  	</div>
  <% end %>
<% end %>

app/views/cars/show.html.erb
<p>
Model name: <%= @car.mname %> </br>
Model Year:	<%= @car.year %> </br>
Color     :	<%= @car.color %> </br>
Mileage   :	<%= @car.mileage %> </br>
Decription:	<%= @car.description %> </br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarListings</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Car Listings: Find a car for you</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
          <li><%= link_to 'Cars', root_path %></li>
          <li><%= link_to 'Manufacturers', manufacturers_path %></li>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_tag do %>
    $(function(){
      $(document).foundation();
    });
  <% end %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/manufacturers/index.html.erb
<h1> Index of Manufacturers </h1>
<h5><%= link_to 'Create a New Manufacturer', new_manufacturer_path %></h5>
<h5> Click on a manufacturer to add a new car</h5>
<% @man_u.each do |man_u| %>
<ul>
<h6> <%= link_to man_u.name, manufacturer_path(man_u.id) %></h3>
</ul>
<% end %>

app/views/manufacturers/new.html.erb
<%= form_for @man_u do |f| %>
	<div>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<p></p>
	<div>
		<%= f.label :country %>
		<%= f.text_field :country  %>
	</div>
	<div>
	<%= f.submit "submit" %>
	<% end %>

	<% if @man_u.errors.any? %>
  	<div id="error_explanation">
    <h4><%= pluralize(@man_u.errors.count, "error") %>: Please review</h4>
  	
  	<ul>
  	<% @man_u.errors.full_messages.each do |msg| %>
  		<li><%= msg %></li>
  	<% end %>
  	</ul>
  	</div>

  <% end %>

  

app/views/manufacturers/show.html.erb
<h4> Manufacturer Name: <%= @man_u.name %> </h4>
<h4> Manufacturer Country: <%= @man_u.country %></h4>
<h4><%= link_to "Create a new #{@man_u.name} Car", new_manufacturer_car_path(@man_u.id)%></h4>